VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iDrupalEntity"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Property Get Table()

End Property

Public Property Get ID() As Long

End Property

Public Property Let ID(lValue As Long)

End Property

Public Property Let Label(vValue As Variant)

End Property

Public Property Get IdField()

End Property

Public Property Get LabelField()

End Property

Public Property Get Label()

End Property

Public Function GetFields()

End Function
